const x = 10

try {
    x = 2
} catch (err) {
    console.log("ðŸš€ ~ file: try_catch.js:8 ~ err:", err)
}